### ISSUE TITLE
Can't update pixel experience ROM

### ISSUE THREAD

**Issue by iashraful** [PixelExperience-Devices/device_xiaomi_violet#13]
I have downloaded the ROM from [here](https://download.pixelexperience.org/violet). 
Version: `PixelExperience_violet-10.0-20200125-1045-OFFICIAL.zip`

But it's says error. I have tried both way. manual update from sdcard(recovery) and system ui.
Also I lost fingerprint auth in my device. Currently, I am using, `PixelExperience_violet-10.0-20200122-1629-OFFICIAL.zip`

**Comment by Turjoy9** [comment]
follow [this method](https://telegra.ph/Flashing-PE-for-the-first-time-using-the-AOSP-Recovery--Or-updating-12-06)

**Comment by iashraful** [comment]
I have tried with factory reset. This image `PixelExperience_violet-10.0-20200125-1045-OFFICIAL.zip` says signature verification failed.

**Comment by dasshubham762** [comment]
Your downloaded file might have corrupted. Don't use IDM/ADM to download updates. Try to download latest build using Google Chrome.

**Comment by iashraful** [comment]
> Your downloaded file might have corrupted. Don't use IDM/ADM to download updates. Try to download latest build using Google Chrome.

But PixelExperience_violet-10.0-20200122-1629-OFFICIAL.zip flashed successfully. And both downloaded using EagleGet. Also I haved tried to download the 181 mb path and update.

**Comment by dasshubham762** [comment]
Try to download once more using Google Chrome and flash again. Btw, if you have decrypted data then fingerprint won't work. 

> > Your downloaded file might have corrupted. Don't use IDM/ADM to download updates. Try to download latest build using Google Chrome.
> 
> But PixelExperience_violet-10.0-20200122-1629-OFFICIAL.zip flashed successfully. And both downloaded using EagleGet. Also I haved tried to download the 181 mb path and update.

**Comment by iashraful** [comment]
OK i'll try again

**Comment by iashraful** [comment]
Fixed the issue.
